# J1MSKY Home Assistant Package
# Drop this into: /config/packages/j1msky_bridge.yaml

rest_command:
  j1msky_bridge_command:
    url: "http://127.0.0.1:8091/command"
    method: POST
    content_type: "application/json"
    payload: '{"command":"{{ command }}"}'
    timeout: 20

input_text:
  j1msky_last_command:
    name: J1MSKY Last Command
    max: 255

script:
  j1msky_send_command:
    alias: J1MSKY Send Command
    mode: queued
    fields:
      command:
        description: Command text for J1MSKY bridge
        example: "play music"
    sequence:
      - service: input_text.set_value
        target:
          entity_id: input_text.j1msky_last_command
        data:
          value: "{{ command }}"
      - service: rest_command.j1msky_bridge_command
        data:
          command: "{{ command }}"

  j1msky_play_music:
    alias: J1MSKY Play Music
    sequence:
      - service: script.j1msky_send_command
        data:
          command: "play music"

  j1msky_pause_music:
    alias: J1MSKY Pause Music
    sequence:
      - service: script.j1msky_send_command
        data:
          command: "pause music"

  j1msky_next_track:
    alias: J1MSKY Next Track
    sequence:
      - service: script.j1msky_send_command
        data:
          command: "next track"

  j1msky_open_command_center:
    alias: J1MSKY Open Command Center
    sequence:
      - service: script.j1msky_send_command
        data:
          command: "open command center"

  j1msky_run_backup:
    alias: J1MSKY Run Backup
    sequence:
      - service: script.j1msky_send_command
        data:
          command: "run backup"

automation:
  - alias: J1MSKY Startup Ping
    id: j1msky_startup_ping
    trigger:
      - platform: homeassistant
        event: start
    action:
      - service: script.j1msky_send_command
        data:
          command: "open command center"

intent_script:
  J1MSKYCommandIntent:
    speech:
      text: "Done. Sending {{ command }} to J1MSKY."
    action:
      - service: script.j1msky_send_command
        data:
          command: "{{ command }}"
